############# English navigation ##############

# main menu
[[main]]
name = "Ohjelma"
url = "/#ohjelma"
weight = 2

[[main]]
name = "Liput"
url = "/#liput"
weight = 3

[[main]]
name = "Puhujat"
url = "/#puhujat"
weight = 5

[[main]]
name = "Yhteystiedot"
url = "/#yhteystiedot"
weight = 6


# footer menu
[[footer]]
name = "Ohjelma"
url = "/#ohjelma"
weight = 2

[[footer]]
name = "Liput"
url = "/#liput"
weight = 3

[[footer]]
name = "Yhteystiedot"
url = "/#yhteystiedot"
weight = 4
